[project]
name = "python-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "pillow>=12.0.0",
    "pptxtoimages>=0.1.14",
    "python-pptx>=1.0.2",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
